#将静态内容部署到GitHub页面的简单工作流程
姓名: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["主要"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#设置GITHUB_TOKEN的权限以允许部署到GitHub页面
permissions:
  contents: read
  pages: write
  id-token: write

#只允许一个并发部署，跳过正在运行和最新排队之间排队的运行。
#但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - 姓名: Checkout
uses: actions/checkout@v4
      - 姓名: Setup Pages
uses: actions/configure-pages@v5
      - 姓名: Upload artifact
uses: action/upload-pages-artifact@v3
和……一起:
          #上传整个资源库
路径: '.'
      - 姓名: 部署到GitHub页面
身份标识: 部署
uses: 操作/部署页面@v4
